services:
  api:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"

  ui:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install streamlit requests && streamlit run frontend/streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - BACKEND_URL=http://api:8000/chat
    ports:
      - "8501:8501"
    depends_on:
      - api
